apiVersion: apps/v1

kind: Deployment

metadata:

  name: mypvc

  labels:

    app: mypvc

spec:

  replicas: 1

  selector:

    matchLabels:

      app: mypvc

  template:

    metadata:
  
      labels:      
  
        app: mypvc

    spec:

      containers:

        - name: myapp

          image: nginx

          volumeMounts:

            - name: myvolume

              mountPath: /usr/share/nginx/html

      volumes:

        - name: myvolume

          persistentVolumeClaim:

            claimName: my-nfs-claim
