apiVersion: v1

kind: PersistentVolume

metadata:

  name: my-nfs-volume

spec:

  persistentVolumeReclaimPolicy: Retain

  capacity:

    storage: 1Gi

  accessModes:

    - ReadWriteMany

  nfs:

      path: /storage

        server: nfs-server.default.svc.cluster.local

#  mountOption:

#    - vers = 4

#    - minorversion = 1

#    - noac
