apiVersion: apps/v1

kind: StatefulSet

metadata:

  name: mystateful

  labels:

    app: mystateful

spec:

  replicas: 5

  selector:

    matchLabels:

      app: mystateful

  template:

    metadata:
  
      labels:      
  
        app: mystateful

    spec:

      containers:

        - name: myapp

          image: nginx
